version: '3.9'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--port", "6379"]
    ports:
      - "6379:6379"
